development:
  adapter: postgresql
  encoding: unicode
  database: 20151029_development
  pool: 5
  username: tf
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: 20151029_test
  pool: 5
  username: tf
  password:
